# Generated by Django 3.1.3 on 2022-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_day_month_now_time_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='api_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
