# Generated by Django 3.1.3 on 2022-05-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220505_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='api_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
