# Generated by Django 3.1.3 on 2022-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220505_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('inout', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='day',
        ),
        migrations.DeleteModel(
            name='month',
        ),
        migrations.DeleteModel(
            name='now',
        ),
        migrations.DeleteModel(
            name='time',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
