# Generated by Django 3.1.3 on 2022-05-12 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220505_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stay',
            old_name='DateTime',
            new_name='dateTime',
        ),
        migrations.AddField(
            model_name='stay',
            name='place',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
