# Generated by Django 3.1.3 on 2022-05-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220513_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
