# Generated by Django 3.1.3 on 2022-05-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220521_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
